"""
Validates retrieval/query.py's actual behavior against the same leakage
rules tests/test_no_leakage.py enforces at the dataset level -- this is the
roadmap's Step 4 requirement to run the leakage rule "against the retrieval
query function," not just the dataset that feeds it.

Separate file from tests/test_no_leakage.py deliberately: that file is
generated by prepare_datasets.py and gets overwritten if it's re-run (see
context/architecture.md) -- hand-adding retrieval-specific assertions to it
would be silently lost.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from retrieval.query import query_analogues, eligibility_mask, _load

REPO_ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture(scope="module")
def candidates():
    _, c = _load()
    return c


@pytest.fixture(scope="module")
def sample_query_dates(candidates):
    """A representative sample across all 3 splits, including some known
    heatwave-episode query dates specifically (the highest-risk case for
    leakage, since same-episode exclusion only matters there)."""
    rng_sample = candidates.groupby("split", group_keys=False).apply(
        lambda g: g.sample(n=min(30, len(g)), random_state=0)
    )
    heatwave_sample = candidates[candidates["target_is_heatwave"]].sample(
        n=min(20, candidates["target_is_heatwave"].sum()), random_state=0
    )
    return pd.concat([rng_sample, heatwave_sample])["query_date"].tolist()


def test_no_future_data_leakage(sample_query_dates, candidates):
    """Rule 1: every returned analogue must chronologically precede the
    query by at least the 19-day buffer, matching test_no_leakage.py's own
    boundary definition."""
    for query_date in sample_query_dates:
        result = query_analogues(query_date, k=5)
        if len(result) == 0:
            continue
        query_row = candidates[candidates["query_date"] == query_date].iloc[0]
        assert (result["query_date"] <= query_row["candidate_latest_start"]).all(), (
            f"Future-data leakage for query {query_date}: "
            f"{result[result['query_date'] > query_row['candidate_latest_start']]}"
        )


def test_split_eligibility(sample_query_dates, candidates):
    """Rule 2: train->train only, val->train only, test->train/val only,
    NEVER same-split (except train, which can only draw from earlier train
    by construction of rule 1)."""
    allowed = {"train": {"train"}, "val": {"train"}, "test": {"train", "val"}}
    for query_date in sample_query_dates:
        query_row = candidates[candidates["query_date"] == query_date].iloc[0]
        result = query_analogues(query_date, k=5)
        if len(result) == 0:
            continue
        bad = ~result["split"].isin(allowed[query_row["split"]])
        assert not bad.any(), (
            f"Split-eligibility violation for {query_row['split']} query {query_date}: "
            f"got splits {result.loc[bad, 'split'].tolist()}"
        )


def test_no_same_episode(sample_query_dates, candidates):
    """Rule 3: a query that is itself part of a qualifying episode must
    never retrieve a candidate from that SAME episode."""
    for query_date in sample_query_dates:
        query_row = candidates[candidates["query_date"] == query_date].iloc[0]
        if pd.isnull(query_row["target_episode_id"]):
            continue
        result = query_analogues(query_date, k=5)
        if len(result) == 0:
            continue
        assert not (result["target_episode_id"] == query_row["target_episode_id"]).any(), (
            f"Same-episode leakage for query {query_date} (episode {query_row['target_episode_id']})"
        )


def test_dedup_respects_episode_cap(sample_query_dates):
    """No more than 2 returned analogues share the same (non-null) episode."""
    for query_date in sample_query_dates:
        result = query_analogues(query_date, k=10)  # ask for more than 5 to stress the cap
        if len(result) == 0:
            continue
        counts = result["target_episode_id"].dropna().value_counts()
        assert (counts <= 2).all(), f"Episode dedup violated for query {query_date}: {counts.to_dict()}"


def test_dedup_respects_temporal_spacing(sample_query_dates):
    """No two returned analogues' query_dates are closer than min_days_apart
    (default 10) -- the fix for the near-duplicate-window problem found
    during manual inspection (see context/decisions.md)."""
    for query_date in sample_query_dates:
        result = query_analogues(query_date, k=5)
        if len(result) < 2:
            continue
        dates = sorted(result["query_date"].tolist())
        gaps = [(dates[i + 1] - dates[i]).days for i in range(len(dates) - 1)]
        assert all(g >= 10 for g in gaps), f"Temporal-spacing dedup violated for query {query_date}: gaps={gaps}"


def test_no_self_retrieval(sample_query_dates):
    """A window can never retrieve itself as an analogue."""
    for query_date in sample_query_dates:
        result = query_analogues(query_date, k=5)
        assert query_date not in result["query_date"].tolist()
